# Generated by Django 4.1.1 on 2022-09-27 09:24

import _queue
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('res', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uni',
            name='Autonomous',
        ),
        migrations.AddField(
            model_name='uni',
            name='Affliation',
            field=models.TextField(default=_queue.Empty),
        ),
    ]
